version: "3.8"
services:
  postgresdb:
    image: postgres:14
    container_name: green_shop_postgres_db
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data      
    env_file:
      - ./config/development.env
  frontend:
    image: "green-shop-frontend-dev"
    container_name: green_shop_frontend_dev
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
  backend:
    image: "green-shop-backend-dev"
    container_name: green_shop_backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target:/usr/local/tomcat/webapps
      - ./tomcat-conf:/usr/local/tomcat/conf       
    depends_on:
      - postgresdb
    env_file:
      - ./config/development.env
volumes:
  pg-data: 
    driver: local